title: Digital Manufacturing
author: Arturo Romano
email: info@q3a.mx
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  We are bringing Digital Manufacturing to the mainstream to Latin America.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
